<!DOCTYPE html>
<html>
<head>
<meta charset="%CHARSET%">
<title>%TITLE%</title>
<meta name="viewport" content="width = device-width, initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0,user-scalable=0" />
<script type="text/javascript" src="http://code.jquery.com/jquery.min.js"></script>
<script type="text/javascript" src="http://code.jquery.com/mobile/latest/jquery.mobile.min.js"></script>
<script type="text/javascript" src="%HIDE_FOLDER%/jqm/jquery.mobile.pagination.js"></script>
<link href="http://code.jquery.com/mobile/latest/jquery.mobile.min.css" rel="stylesheet" type="text/css" />
<link href="%HIDE_FOLDER%/jqm/jquery.mobile.pagination.css" rel="stylesheet" type="text/css" />
<link href="%HIDE_FOLDER%/css/reset.css" rel="stylesheet" type="text/css" />
<link href="%HIDE_FOLDER%/css/base.css" rel="stylesheet" type="text/css" />
<meta name="apple-mobile-web-app-capable" content="yes" />
<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
</head>
<body onload="setTimeout('scrollTo(0,1)',100)">
<div data-role="page" id="home">
</div>
</body>
</html>