<!DOCTYPE html>
<html>
<head>
<meta charset="%CHARSET%">
<title>%FILENAME%</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0,user-scalable=0" />
</head>
<body style="margin: 0px; padding: 0px;">
	<video id="embedMovie" controls>
		<source src="%FILENAME%" type='video/mp4; codecs="avc1.42E01E, mp4a.40.2"' />
	</video>
	<br />
	<a target="_blank" href="%FILENAME%">download %FILENAME%</a>
</body>
</html>
